sudo: required
 
  
language:
  - cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install libgtest-dev -y
  - sudo apt-get install cmake
  - sudo pip install codecov
  - sudo pip install lcov
install:
  - pwd
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - sudo mkdir /usr/local/lib/gtest
  - sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
  - sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
  
script:
  - cd /home/travis/build/leoWuTmRobot/test_travis_ci
  - cmake ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .
  - make
  - make test_ci_coverage
  
after_success:
    - codecov -t 99101c41-6dde-4ff9-b9d6-60cbb5361751 -X gcov
