
name : c++_CI_test

on:
  push:
  schedule:
  - cron: 30 16 * * *
  
jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          sudo apt-get install libgtest-dev -y
          sudo apt-get install cmake
          sudo apt-get install lcov
          sudo pip install codecov
    -name : check current folder path
     run: pwd
    -name : install google test
     run: |
         cd /usr/src/gtest
         sudo cmake CMakeLists.txt
         sudo make
         sudo cp *.a /usr/lib
         sudo mkdir /usr/local/lib/gtest
         sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
         sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
     -name : run test
      run: |
          cmake ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .
          make
          make test_ci_coverage
